source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StyledString_Example', :exclusive => true do
  pod "StyledString", :path => "../"
end

target 'StyledString_Tests', :exclusive => true do
  pod "StyledString", :path => "../"

  
end
