source 'https://github.com/CocoaPods/Specs.git'
workspace 'StyledStringExample.xcworkspace'
use_frameworks!

pod 'StyledString', :path => '../'

target 'StyledStringExample' do
  platform :ios, '8.0'
  project 'StyledStringExample.xcodepoj'
end

target 'StyledStringTv' do
  platform :tvos, '9.0'
  project 'StyledStringTv.xcodepoj'
end

